# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
nutritionplans:
    path: /{resource}{slash}
    requirements:
        resource: "nutritionplans"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]

actionincluded:
    path: /{resource}{slash}{action}
    requirements:
        resource: "nutritionplans"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]